#!/usr/bin/env bash
# install nginx and change index
apt-get -y update && apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
CONFIG_PATH=/etc/nginx/sites-available/default
OLD="server_name _;"
NEW="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

sed -i "/$OLD/a\\$NEW" $CONFIG_PATH
NEW="\\\t\tadd_header X-Served-By $HOSTNAME always;"
sed -i "48i $NEW" $CONFIG_PATH
service nginx restart
