#!/usr/bin/env bash
# nginx with nginx user
chown -R nginx:nginx /etc/nginx/
sudo -u nginx -s
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
